cd Assets
git clone https://github.com/Ellyality/package_naughty_attributes.git
git clone https://github.com/Ellyality/package_randomness.git
git clone https://github.com/Ellyality/package_mapping.git
git clone https://github.com/Ellyality/package_display.git
git clone https://github.com/Ellyality/package_litenetlib.git
git clone https://github.com/Ellyality/package_multiplayer_core.git
git clone https://github.com/Ellyality/package_sqlite.git
git clone https://github.com/Ellyality/package_socketio.git
git clone https://github.com/Ellyality/package_utility.git
git clone https://github.com/Ellyality/package_character.git
git clone https://github.com/Ellyality/package_sdf.git
git clone https://github.com/Ellyality/package_smoke.git
git clone https://github.com/Ellyality/package_aeroUI.git
git clone https://github.com/Ellyality/package_unity_free_camera.git
git clone https://github.com/Ellyality/package_xlua.git
git clone https://github.com/Ellyality/package_unibus.git
git clone https://github.com/Ellyality/package_crest.git
git clone https://github.com/Ellyality/package_ffmpeg_bind2.git
git clone https://github.com/Ellyality/package_particle_effect2D.git
git clone https://github.com/Ellyality/package_volumetric_lights.git
git clone https://github.com/Ellyality/package_bulletsharp.git
git clone https://github.com/Ellyality/package_delaunay.git
git clone https://github.com/Ellyality/package_heap_explorer.git
git clone https://github.com/Ellyality/package_uniGif.git
git clone https://github.com/Ellyality/package_custom_toolbar.git
git clone https://github.com/Ellyality/package_smart_inspector.git
git clone https://github.com/Ellyality/package_smart_hierarchy.git
git clone https://github.com/Ellyality/package_road_architect.git
git clone https://github.com/Ellyality/package_http.git
git clone https://github.com/Ellyality/package_hex_tiles.git
git clone https://github.com/Ellyality/package_pixel_camera.git
pause